### ISSUE TITLE
LQUERY not found

### ISSUE THREAD

**Issue by thoni56** [wshito/asciidoctor-chunker#1]
I was trying out the chunker, building from source, but got the following:

    Component :LQUERY not found, required by #<SYSTEM "asciidoctor-chunker">.
    Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                              {10005585B3}>:

Am I missing something? `ros setup` finished without errors. I'm on ElementaryOS, an Ubuntu derivative.

**Comment by thoni56** [comment]
Ok, as a noob in common lisp, I had to learn how to install packages:

    $ ros run
    * (ql:quickload '(:lquery))

Then the tests passed.

**Comment by wshito** [comment]
Thanks for the follow up, @thoni56.  I added the instruction how to install the dependencies.

**Comment by thoni56** [comment]
Nice. Thanks! Glad I could help.
