### ISSUE TITLE
Unclear on meaning of warnings from new chunker

### ISSUE THREAD

**Issue by oddhack** [wshito/asciidoctor-chunker#10]
First, thanks very much for doing the JS version. The performance increase is huge, and will make it viable to include the chunker in our specification CI, which wasn't practical with the roswell version due to 4-5 CPU minute runtimes.

There are a couple of warnings we're getting that I'm unclear of the meaning of, using the 0.9 release (maybe they were present in the old version as well and I just didn't notice). Here's an excerpt from the build:

```
node /home/tree/git/vulkan/scripts/asciidoctor-chunker/asciidoctor-chunker.js /home/tree/git/vulkan/gen/out/html/prechunked.html -o /home/tree/git/vulkan/gen/out/html

Woops, unknown contents here to be processed.
Woops, unknown contents here to be processed.
Successfully chunked! => /home/tree/git/vulkan/gen/out/html/index.html

    Local file liked from the document is missing: /home/tree/git/vulkan/gen/out/html/chunked.css?4
    Local file liked from the document is missing: /home/tree/git/vulkan/gen/out/html/chunked.js?4
```

I'm unclear what the 'Woops' message is complaining about. Our HTML is the output of asciidoctor so we don't have very much control over it, aside from our CSS - but if this is a problem, it would help to be given a pointer to what's causing the problem so we can try and fix it.

The 'Local file liked' (linked?) message is complaining about missing files, but the files (chunked.css / chunked.js) are present, referred to as follows:

> <script src="chunked.js?4"></script>

I'll admit that I'm unsure about the purpose and validity of the '?4' following the script name - these files didn't come from us originally, and are something of a black box. I'm checking with the original author about that. If it's legal URL syntax to have a \<script> filename followed by '?4' - which I can't immediately establish from the W3C docs - then the chunker should recognize that and strip off the trailing attributes, or whatever they are, for purposes of checking existence of the file.

Finally, kudos on collapsing imbedded CSS to external files referred to by all the chunks. Our CSS is pretty large, so this represents a meaningful savings in the chunked output size!

**Comment by wshito** [comment]
I am happy to hear it's helping your project!  And thank you for your feedback.

First of all, sorry for the 'Woops' message, it's really a bad taste, isn't it?😅  The message is solely for the developer of asciidoctor-chunker (which is myself) because the program encountered the unexpected content.  The single html generated with Asciidoctor puts all the contents in `<div id="#content"></div>`.  All the divs within that should have a class name either `preamble`, `partintro`, `sect1`, or `sect0` at least as far as I know.  Obviously, your document has other than those.  Can you check the single html generated and find out what are those?

About the missing message, asciidoctor-chunker simply assumes the last part of the path segment as a filename so it looked for `chunked.css?4` instead of `chunked.css`.  I was not expecting parameter passing to the local files.  I thought it is only the HTTP things.  But I guess it is valid usage since HTML documents are supposed to put on the web and are published by HTTP server.  I will fix it to ignore the parameters.

**Comment by wshito** [comment]
Hi, the local file's missing bug should be fixed now.  Can you check with the attached bundle?

[asciidoctor-chunker.js.zip](https://github.com/wshito/asciidoctor-chunker/files/6015793/asciidoctor-chunker.js.zip)

About the woops message, I will wait for what you got under `div#content` node.

**Comment by wshito** [comment]
@oddhack I found the causing element in the single html of [your project document.](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html).  It's the script tag that prints out 'Loading… please wait.' message.  I will fix the code to include custom tags inserted by users.

**Comment by wshito** [comment]
@oddhack Please test with the pre-release bundle from [here](https://github.com/wshito/asciidoctor-chunker/releases).  It should cover all your cases.

In the single html published [here](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html), all the links in the toc have full URL with `http:` prefix.  Asciidoctor-chunker leaves non-relative links untouched so I added asciidoctor-chunker to print the message to warn it.

The 'Oops' message is replaced with more appropriate one.  Your document includes a custom script element that prints 'loading' message.  I don't think you need that in chunked html so by default asciidoctor-chunker ignores it.  If you want to include it, use `--no-strictMode` option.

If you have any more problems let me know!

**Comment by oddhack** [comment]
Thanks! I will check in the next day or two and report back. BTW the script author says that the trailing '?4' on the local script URLs is a workaround to defeat browser caching, so intentional and apparently meaningful even though the script itself doesn't do anything with the parameters.

**Comment by oddhack** [comment]
> @oddhack Please test with the pre-release bundle from [here](https://github.com/wshito/asciidoctor-chunker/releases). It should cover all your cases.

I gave the v1.0.0-alpha.0 bundle a try, and it's looking good. I will need to get more Khronos people to try out and sign off on the updated chunked spec before we ship it, and we might have a little more feedback from that. The only thing I noticed which was slightly odd, was that the filename <-> chapter map changed by one chapter relative to the roswell chunker. This isn't actually a problem since we add chapters on a regular basis anyway, just something I noticed because a directory diff of roswell and JS chunker output was comparing the wrong files.

However, I'm confused by this:

> In the single html published [here](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html), all the links in the toc have full URL with `http:` prefix. Asciidoctor-chunker leaves non-relative links untouched so I added asciidoctor-chunker to print the message to warn it.

I took a look at the HTML markup and all the ToC markup appears to use relative URLs, e.g.

```
<div id="toc" class="toc2">
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a href="#preamble">1. Preamble</a></li>
<li><a href="#introduction">2. Introduction</a>
<ul class="sectlevel2">
<li><a href="#introduction-conventions">2.1. Document Conventions</a></li>
</ul>
</li>
<li><a href="#fundamentals">3. Fundamentals</a>
<ul class="sectlevel2">
<li><a href="#fundamentals-host-environment">3.1. Host and Device Environment</a></li>
```

And, the right thing is happening in the updated ToC in chunked output. Were you referring to another part of the HTML having absolute URLs?

**Comment by wshito** [comment]
About the relative links of the toc, you are right.  The source on the web has relative links.  Maybe Safari saves the generated html from the DOM when I save the page on the local drive.  I should make the link check function as optional to make program run faster.

About the difference of chapter outcome, I could not nail down the differences.  The reason I started to write JS version is that I could not setup lisp environment with my latest MacOS.  So I can not really run both and compare.  I checked the Lisp code but  I couldn't find anything.  I wrote the JS version from scratch without really looking at the Lisp  version so maybe there is some small differences in outcome.

Just please make sure the JS version does not miss any parts, chapters, and sections while extracting.  With the test case I made, it seems working just fine though.

About the query parameters of the script file, it is clever!  I didn't know that hack.  I should put the query string back into the extracted page.  I simply trimmed it in the current version.

**Comment by oddhack** [comment]
I think we are good for now. We have some internal review going on but I'm not expecting substantive feedback (other than "hey, this is really fast!" :-). I am going to close this issue and keep an eye on the repo for the 1.0 release - will reopen it or open a new one if we find anything else worth mentioning. Thanks again!

**Comment by oddhack** [comment]
Oh, BTW, I'm not sure I was clear enough about the URL parameter (the '?4') being used to "defeat browser caching". The author said the intent was just to increment the number every time there was a change in the target URL, rather than it being anything automatic.
