### ISSUE TITLE
Installing and running from somewhere other than $HOME/common-lisp?

### ISSUE THREAD

**Issue by oddhack** [wshito/asciidoctor-chunker#4]
I looked for a support forum and didn't find one; so apologies for what is probably a Roswell/CL newb question here. We would like to install asciidoctor-chunker as part of the toolchain for the documents we develop, and include it in the git repository for those documents, rather than require everyone working on the docs to install it under their personal $HOME/common-lisp, outside the scope of our repo.

Trying this generated a flood of incomprehensible errors, though, and a little investigation appeared to show that running the chunker script from another directory requires doing a bunch of configuration of roswell itself. So I'm wondering if there's some straightforward way to wrap all the needed runtime/path lookup configuration, and the invocation of asciidoctor-chunker itself in a shell script - and if so, if such a script already exists? This would make supporting our developers' use of the chunker considerably easier.

**Comment by koji-kojiro** [comment]
Have you tried [`qlot`](https://github.com/fukamachi/qlot)?

**Comment by oddhack** [comment]
@koji-kojiro thanks; I will take a look at it.

**Comment by wshito** [comment]
@oddhack if I understand you,  you want to place your asciidoc document files anywhere on your hard drive, right?

`asciidoctor-chunker.ros` is just a shell script that starts up the lisp implementation and load asciidoctor-chunker lisp program (which is located under `$HOME/common-lisp`).  As far as the document path passed to the script is reachable from wherever the directory you are invoking it from, the program should run properly.

If you can give me the directory layout and the commands you typed, I can help you more.

**Comment by oddhack** [comment]
Sorry, I was not clear. I'd like to install all the roswell/CL files in the asciidoctor project folder, rather than my home directory, so they can be prepackaged for other people building the project out of our shared repository.

**Comment by wshito** [comment]
@oddhack I am sure it is possible but I think the cost of changing all the configurations does not meet the benefit of it.  How about providing roswell and asciidoctor-chunker in one docker image?

**Comment by oddhack** [comment]
That will work for some use cases, but mostly people just pull the repo on their own workstation, not in a VM image. I don't know anywhere near enough about roswell/CL to understand why everything it uses has to go into in a single specific directory under $HOME, but it seems like a weird restriction.

**Comment by wshito** [comment]
You might be able to understand the way it is if you compare with other languages.  You wouldn't install Ruby runtime under asciidoctor project directory, right?  Or you wouldn't install Node.js or nvm in your JavaScript project, right?

**Comment by wshito** [comment]
@oddhack The completely re-imeplmented JavaScript version of Asciidoctor-Chunker is now released.  It runs under NodeJS.  It should be easy to setup so I will close this issue.  Please open a new issue if you find any problems with the new version.  Thank you.
