### ISSUE TITLE
Pressing left or right arrow key causes navigation

### ISSUE THREAD

**Issue by zopsicle** [wshito/asciidoctor-chunker#41]
The left and right arrow keys, when used together with the shift key, normally adjust which text is currently selected. However, in documents generated by asciidoctor-chunker, such as the [Vulkan specification](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap4.html), this causes the browser to navigate to another chapter.

# Steps to reproduce

 1. Select text.
 2. Hold shift and press the right arrow key.

# Expected behavior

The selection is extended by one character to the right, as on any regular web page.

# Actual behavior

The browser navigates to another page.

**Comment by wshito** [comment]
@chloekek Thank you for your  contribution!
