### ISSUE TITLE
Support more fine grained chunks

### ISSUE THREAD

**Issue by Zingam** [wshito/asciidoctor-chunker#5]
Support more fine grained chunks like described here:
https://github.com/KhronosGroup/Vulkan-Docs/issues/578#issuecomment-443196901

"Wouldn't splitting the chapters at a subtitle level such as "31.7. Sparse Resource API" be preferable (if possible) or even at "31.7.1. Physical Device Features" as the reader of the specification won't have to scroll as much ad will be easier to find/not to lose the location he wants tot read?"

For example in this doc: https://renderdoc.org/vkspec_chunked/chap41.html#extensions the chunks (at chapter level) are too huge still.

**Comment by wshito** [comment]
Sorry for the delay.  I've just noticed your comment now.  Isn't this feature already implemented in the asciidoctor project although experimental?  I read something about MultipageHtml5Converter extension in their issue.

**Comment by wshito** [comment]
Hi, @Zingam 

I have released the new JavaScript version of asciidoctor-chunker.  Your request on fine grained chunks are now supported.  Although it is a bit late, I hope you find it useful.  Your comment and feedback are very much welcome.  😊
