### ISSUE TITLE
Complaints about cl-fad

### ISSUE THREAD

**Issue by oddhack** [wshito/asciidoctor-chunker#6]
When using the chunker, I consistently get this:

WARNING: System definition file #P"/home/jon/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-fad-20180430-git/cl-fad.asd" contains definition for system "cl-fad-test". Please only define "cl-fad" and secondary systems with a name starting with "cl-fad/" (e.g. "cl-fad/test") in that file.
; compiling file "/home/jon/common-lisp/asciidoctor-chunker/src/plump.lisp" (written 04 NOV 2018 07:45:00 PM):

I don't know if this is a problem with this repo or the underlying cl-fad package, though.

**Comment by oddhack** [comment]
I asked over on https://github.com/roswell/roswell/issues/348 as well, and was advised that this warning was something that the chunker could suppress. Is this something you would consider adding?

**Comment by wshito** [comment]
I suppose it is the warning for cl-fad package developer.  But I am not an expert on this.  When I have time, I will try to implement without cl-fad.  At the moment please just ignore the warning message.  Warning is not really an error so you can simply ignore it.
