### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by bwittman** [wshito/asciidoctor-chunker#9]
AsciiDoctor-Chunker seems to be running out of memory.  I have a 21 chapter textbook that I've converted into AsciiDoctor.  For months, I've been using AsciiDoctor-Chunker successfully to chunk the HTML output into individual chapters.

Today, after making some updates to chapter 14, chapter 17 suddenly crashes the chunker with the following error:

```
Heap exhausted during garbage collection: 64 bytes available, 128 requested.
Gen  Boxed Unboxed   LgBox LgUnbox  Pin       Alloc     Waste        Trig      WP GCs Mem-age
fatal error encountered in SBCL pid 472(tid 0x7f82b6854b80):
GC invariant lost, file "gencgc.c", line 472
```

I can comment out a few paragraphs of AsciiDoctor source pretty much anywhere inside of chapter 17 and AsciiDoctor-Chunker works without problems.  It seems like I'm running out of memory.  Is a memory leak possible?  Is there a way to run AsciiDocter-Chunker with a larger heap size?

**Comment by wshito** [comment]
Here is the references how to increase the heap.

- [roswell Wiki: How can I extend the dynamic space size? (sbcl-specific)](https://github.com/roswell/roswell/wiki/FAQ#how-can-i-extend-the-dynamic-space-size-sbcl-specific) 
- [Stackoverflow: How to Configure SBCL to Use More RAM When Started Through Emacs?](https://stackoverflow.com/questions/7181183/how-to-configure-sbcl-to-use-more-ram-when-started-through-emacs)

**Comment by bwittman** [comment]
Thanks!
